from __future__ import annotations

import os
from pathlib import Path


# ---------------------------------------------------------------------------
# PROJECT PATHS
# ---------------------------------------------------------------------------

# Anchor all paths to the project root rather than relying on the terminal's
# current working directory.
#
# Expected structure:
#
# EcoSight/
# ├── src/
# │   └── prompt_engineering.py
# ├── docs/
# ├── models/
# └── data/
#
PROJECT_ROOT = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# NAIVE PROMPT
# ---------------------------------------------------------------------------

# Deliberately vague prompt used as a comparison against the engineered
# version below.
NAIVE_PROMPT = "Write about the energy data."

# ---------------------------------------------------------------------------
# ENGINEERED PROMPT
# ---------------------------------------------------------------------------

def build_engineered_prompt(context: dict) -> tuple[str, str]:
    """
    Build the instruction prompt and user prompt for the OpenAI model.

    Returns:
        tuple[str, str]:
            (instructions, user_prompt)

    Prompt engineering techniques demonstrated:
      - Role definition
      - Audience specification
      - Tone control
      - Grounding using real numerical results
      - Explicit output structure
      - Length constraints
      - Anti-hallucination constraints
      - Technical-jargon handling
    """

    instructions = (
        "You are a senior energy and data analyst preparing a briefing for "
        "IntelliGen's leadership team. The audience is business-savvy but "
        "does not have specialist knowledge of machine learning or data "
        "science. "
        "\n\n"
        "Write in clear, professional, plain English. "
        "When you use a technical term such as MAE, Random Forest, LSTM, "
        "clustering, reinforcement learning, or SHAP, briefly explain what "
        "it means in the same sentence. "
        "\n\n"
        "Your job is to interpret the supplied EcoSight results accurately, "
        "not to invent additional findings."
    )

    user_prompt = f"""
Prepare a short management briefing of approximately 250-350 words about
EcoSight's energy-monitoring results for this analysis period.

IMPORTANT GROUNDING RULES:
- Base the briefing ONLY on the figures provided below.
- Do not invent, estimate, infer, or fabricate numerical results.
- If the data does not support a conclusion, state that clearly.
- Explain the business meaning of the results rather than simply repeating
  the numbers.
- Use language understandable to a non-technical stakeholder.

Use these EXACT section headings:

1. What we measured
2. Key findings
3. Business impact
4. Caveats / limitations

ECO SIGHT RESULTS
-----------------

Forecasting performance:
- Random Forest MAE: {context['rf_mae']:.1f} {context['unit']}
- LSTM MAE: {context['lstm_mae']:.1f} {context['unit']}

Demand-pattern analysis:
- Number of distinct daily demand patterns: {context['n_clusters']}
- Number of days analysed: {context['n_days']}

Scheduling optimisation:
- Carbon reduction achieved: {context['carbon_saving_pct']:.1f}%
- Scheduler type: {context['scheduler_type']}
- Comparison baseline: naive "start immediately" scheduling

Explainability:
- Most influential predictive feature:
  {context['top_feature']}

When discussing forecasting performance, remember that MAE means
Mean Absolute Error: the average absolute difference between predicted
and actual electricity demand. Therefore, lower MAE indicates better
forecast accuracy.

Do not introduce numbers that are not contained in this prompt.
""".strip()

    return instructions, user_prompt


# ---------------------------------------------------------------------------
# OPENAI API
# ---------------------------------------------------------------------------

def call_chatgpt(
    instructions: str,
    user_prompt: str,
    model: str = "gpt-5.6",
    max_output_tokens: int = 800,
    mock: bool | None = None,
) -> str:
    """
    Send a prompt to ChatGPT through the OpenAI Responses API.

    If OPENAI_API_KEY is missing, or mock=True is supplied, the function
    returns a placeholder instead of making an API request.

    Args:
        instructions:
            High-level role, audience, tone, and behavioural instructions.

        user_prompt:
            The actual task and grounded EcoSight results.

        model:
            OpenAI model to use. Defaults to gpt-5.6.

        max_output_tokens:
            Maximum number of output tokens generated by the model.

        mock:
            True  -> always use mock response.
            False -> always attempt API call.
            None  -> automatically use mock if no API key exists.

    Returns:
        str:
            Generated response or clearly-labelled mock/error message.
    """

    api_key = os.environ.get("OPENAI_API_KEY")

    # Automatically enter mock mode when an API key has not been configured.
    use_mock = mock if mock is not None else (api_key is None)

    if use_mock:
        return (
            "[MOCK RESPONSE -- no OPENAI_API_KEY is configured, so this is "
            "a placeholder showing where a real ChatGPT-generated report "
            "would appear. Set the OPENAI_API_KEY environment variable and "
            "re-run the program to receive a real response.]\n\n"
            f"(Instructions used: {len(instructions)} chars, "
            f"user prompt used: {len(user_prompt)} chars)"
        )

    try:
        # Import here rather than globally so mock mode can still run even if
        # the OpenAI package has not yet been installed.
        from openai import OpenAI

        client = OpenAI(api_key=api_key)

        response = client.responses.create(
            model=model,

            # In the Responses API, "instructions" serves the role normally
            # associated with the system prompt.
            instructions=instructions,

            # The user's request/data.
            input=user_prompt,

            # Keeps the generated management report bounded.
            max_output_tokens=max_output_tokens,
        )

        # Responses API provides output_text as a convenient way of obtaining
        # the generated text from the response object.
        return response.output_text

    except Exception as e:
        return f"[ERROR calling OpenAI API: {e}]"


# ---------------------------------------------------------------------------
# GENERATE BOTH PROMPT VERSIONS
# ---------------------------------------------------------------------------

def generate_report(
    context: dict,
    mock: bool | None = None,
) -> dict:
    """
    Run both the naive and engineered prompts against ChatGPT.

    This allows the outputs to be compared side-by-side and provides
    evidence that prompt engineering changes the quality and usefulness
    of the generated report.
    """

    # ---------------------------------------------------------------
    # 1. NAIVE VERSION
    # ---------------------------------------------------------------

    naive_response = call_chatgpt(
        instructions="You are a helpful assistant.",
        user_prompt=NAIVE_PROMPT,
        mock=mock,
    )

    # ---------------------------------------------------------------
    # 2. ENGINEERED VERSION
    # ---------------------------------------------------------------

    engineered_instructions, engineered_prompt = (
        build_engineered_prompt(context)
    )

    engineered_response = call_chatgpt(
        instructions=engineered_instructions,
        user_prompt=engineered_prompt,
        mock=mock,
    )

    return {
        "naive_prompt": NAIVE_PROMPT,
        "naive_response": naive_response,

        "engineered_instructions": engineered_instructions,
        "engineered_user_prompt": engineered_prompt,
        "engineered_response": engineered_response,
    }


# ---------------------------------------------------------------------------
# SAVE COMPARISON
# ---------------------------------------------------------------------------

def save_comparison_markdown(result: dict, out_path: str) -> None:
    """
    Save the naive-versus-engineered prompt comparison as Markdown.
    """

    md = f"""# Prompt Engineering Comparison

## Naive Prompt

**Prompt:**

`{result['naive_prompt']}`

### Response

{result['naive_response']}

---

## Engineered Prompt

### Instructions

```text
{result['engineered_instructions']}

## Why the engineered version is better

The naive prompt gives the model no data to report on, no audience, no
structure, and no length limit -- so it can only produce generic, made-up
content about "energy data" in the abstract. It has no way to be accurate
about EcoSight specifically, because it was never told anything about
EcoSight.

The engineered prompt fixes this by:
- **Grounding**: the actual numbers are injected directly into the prompt,
  so the model reports on real results rather than inventing plausible
  ones -- critical for factual reliability in a business context.
- **Role and audience framing**: told who it's writing for (non-technical
  leadership), which shapes tone and how it explains jargon.
- **Explicit structure**: named sections make the output predictable and
  easy to drop into a report or slide.
- **Explicit constraints**: a word count keeps it usable in a real
  briefing rather than a rambling essay.
"""
    Path(out_path).write_text(md)
    print(f"Saved prompt comparison to {out_path}")


if __name__ == "__main__":
    # Example context -- in the full pipeline this would be populated from
    # the actual saved results of forecasting.py, clustering.py, and
    # scheduler.py / rl_scheduler.py rather than hardcoded.
    example_context = {
        "rf_mae": 393.4,
        "lstm_mae": 494.5,
        "unit": "MW",
        "n_clusters": 2,
        "n_days": 6027,
        "carbon_saving_pct": 14.8,
        "scheduler_type": "RL",
        "top_feature": "lag_168 (demand at the same hour, one week earlier)",
    }

    result = generate_report(example_context)

    print("=== NAIVE PROMPT RESPONSE ===")
    print(result["naive_response"])
    print("\n=== ENGINEERED PROMPT RESPONSE ===")
    print(result["engineered_response"])

    (PROJECT_ROOT / "docs").mkdir(exist_ok=True)
    save_comparison_markdown(result, str(PROJECT_ROOT / "docs" / "prompt_comparison.md"))